### ISSUE TITLE
connection to IBM COS throws an error local & in paas when uploading image

### ISSUE THREAD

**Issue by RabidAnubis** [IBMRedbooks/IBMRedbooks-SG248385-Cloud-Object-Storage-as-a-Service#4]
in paas it looks like this
Error: connect ECONNREFUSED 169.254.169.254:80
   at Object.exports._errnoException (util.js:1022:11)
   at exports._exceptionWithHostPort (util.js:1045:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

locally it looks like this
NoSuchKey: The specified key does not exist.
   at Request.extractError (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/services/s3.js:577:35)
   at Request.callListeners (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
   at Request.emit (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
   at Request.emit (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/request.js:683:14)
   at Request.transition (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/request.js:22:10)
   at AcceptorStateMachine.runTo (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/state_machine.js:14:12)
   at /home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/state_machine.js:26:10
   at Request.<anonymous> (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/request.js:38:9)
   at Request.<anonymous> (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/request.js:685:12)
   at Request.callListeners (/home/bowiel/COS-WebGallery/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

**Comment by sbollers** [comment]
When testing locally did you create the C:\Users\\<username>\\.aws\credentials file with: aws_access_key_id and aws_secret_access_key key/value pairs?

**Comment by sbollers** [comment]
See the fork for how to use a aws-config to encapsulate credentials in a json file.

**Comment by lee-zhg** [comment]
Hi sbollers, I am not sure what to do for "You need to setup IBM COS credentials for the application". Appreciate if you could explain. Where should aws_access_key_id and aws_secret_access_key come from? Are they covered in redbook? Thank you

**Comment by lee-zhg** [comment]
I found the following statements in redbook; "Select the account name, and then click Show Credentials at the left side of the panel, and click the Show link next to Credentials. The Access Key ID and Secret Access Key are displayed (Figure 3-5)."

The photo in the redbook shows you are in SoftLayer UI. Currently, I connect to through bluemix. Is it possible to identify the Access Key ID and Secret Access Key within bluemix UI? Thanks
